### ISSUE TITLE
solved-stats-per-user.sql - what is not_op and op column?

### ISSUE THREAD

**Issue by konradsopala** [SidVal/discourse-data-explorer#45]
Pretty much the questions as in the title. What is not_op and op i solved-stats-per-user.sql query?

**Comment by SidVal** [comment]
If you are the "op", you are the author of the topic.
If you are not, you are not the author.

About: https://github.com/SidVal/discourse-data-explorer/blob/queries/queries/solved-stats-per-user.sql

**Comment by konradsopala** [comment]
Thanks a lot for help!
